config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :posts
  root 'static#home'
  get 'static/home'

  resources :users, only: [:new, :create, :edit, :update]
  resources :users, only: :show, param: :slug
  resource :session, only: [] do
    get :new, path: :sign_in
    post :create, path: :sign_in
    delete :destroy, path: :sign_out, as: :sign_out
  end

  resources :articles, only: [:index, :show,]
  resources :users do
    resources :articles, only: [:new, :create, :edit, :update, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  has_rich_text :body

  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true

  scope :desc_order, -> { order(updated_at: :desc)}
end

app/models/cat.rb
class Cat < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :articles, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 6 }, if: -> { new_record? }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  # GET /articles
  def index
    @pagy, @articles = pagy(Article.all, items: 5)
  end

  # GET /articles/1
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  def create
    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      redirect_to user_path(current_user), notice: "Article was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to @article, notice: "Article was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy!
    redirect_to articles_url, notice: "Article was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :body, :user_id)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: %i[ show edit update destroy ]

  # GET /cats
  def index
    @cats = Cat.all
  end

  # GET /cats/1
  def show
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats
  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to @cat, notice: "Cat was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /cats/1
  def update
    if @cat.update(cat_params)
      redirect_to @cat, notice: "Cat was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /cats/1
  def destroy
    @cat.destroy
    redirect_to cats_url, notice: "Cat was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cat_params
      params.require(:cat).permit(:breed)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: "Post was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Post was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: "Post was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = login(params[:email], params[:password], params[:remember])
    if user
      redirect_back_or_to root_path, notice: "Successfully logged in"
    else
      flash.now[:notice] = "Invalid email/password combination"
      render :new, status: :see_other
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: "Logged out"
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/controllers/users/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  # GET /articles
  def index
    @pagy, @articles = pagy(Article.desc_order, items: 5)
  end

  # GET /articles/1
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  def create
    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      redirect_to user_path(current_user), notice: "Article was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @user.article.update(article_params)
      redirect_to @user.article, notice: "Article was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy!
    redirect_to articles_url, notice: "Article was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :body, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]

  def show
    @user = User.friendly.find(params[:slug])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: "Signed up!"
    else
      render :new, status: :see_other # for Turbo
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "Profile updated"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar_path(user, options = {})
    size = options[:size] || 32

    hash = Digest::MD5.hexdigest(user.email.downcase)
    "https://secure.gravatar.com/avatar/#{hash}.png?s=#{size}"
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_article.html.erb
<%= turbo_frame_tag dom_id(article) do %>
  <article id="<%= dom_id(article) %>" class="mb-3">
    <h2><%= link_to article.title, article_path(article) %></h2>
    Last updated: <%= article.created_at %>
    <p><%= article.body %></p>
    <div>
      <% if logged_in? == true %>
        <%= link_to "Edit", edit_user_article_path(current_user, article) %> |
        <%= link_to "Delete", article, method: :delete, data: { confirm: "Are you sure? " } %>
      <% end %>
    </div>
  </article>
<% end %>

app/views/articles/_excerpt.html.erb
<article id="<%= dom_id(article) %>" class="mb-3 mx-2">
  <h2><%= link_to article.title, article_path(article) %></h2>
  Author: <%= article.user.name %> | Posted: <%= article.created_at %>
  <p><%= article.body %></p>
  <div>
    <% if logged_in? && article.user_id == current_user.id %>
      <%= link_to "Edit", edit_user_article_path(current_user, article) %> |
      <%= link_to "Delete", article, method: :delete, data: { "turbo-confirm": "Are you sure? " } %>
    <% end %>
  </div>
</article>
<hr />

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation" class="alert alert-danger mb-4 mx-3" role="alert">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <article class="card-body">
    <div class="form-group mb-3">
      <%= form.label :title, class: "form-label" %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :body, "Article", class: "form-label" %>
      <%= form.rich_text_area :body, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.submit class: "btn btn-primary" %>
    </div>
<% end %>
</article>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= turbo_frame_tag dom_id(@article) do %>
  <%= render "form", article: @article %>
<% end %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center mb-2">Articles</h1>

<div id="articles">
  <% @articles.order(created_at: :desc).each do |article| %>
    <%= render partial: "articles/excerpt", locals: { article: article } %>
  <% end %>
</div>

<%#= link_to "New article", new_article_path %>
<%= pagy_bootstrap_nav(@pagy).html_safe %>

app/views/articles/new.html.erb
<div class="row flex-column justify-content-center align-content-center mt-5">
  <div class="col-md-12">
    <div class="card col-md-8 mx-auto shadow-sm p-3">
      <h1 class="card-title text-center">New article</h1>

      <%= render "form", article: @article %>

      <div>
        <%= link_to "Back to articles", articles_path %>
      </div>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<%= turbo_stream_from @article %>

<%= render @article %>

app/views/cats/_cat.html.erb
<div id="<%= dom_id cat %>" class="scaffold_record">
  <p>
    <strong>Breed:</strong>
    <%= cat.breed %>
  </p>

  <p>
    <%= link_to "Show this cat", cat %>
  </p>
</div>

app/views/cats/_form.html.erb
<%= form_with(model: cat) do |form| %>
  <% if cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
        <% cat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :breed %>
    <%= form.text_field :breed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cats/edit.html.erb
<h1>Editing cat</h1>

<%= render "form", cat: @cat %>

<br>

<div>
  <%= link_to "Show this cat", @cat %> |
  <%= link_to "Back to cats", cats_path %>
</div>

app/views/cats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cat</h1>

<div id="cats">
  <%= render @cats %>
</div>

<%= link_to "New cat", new_cat_path %>

app/views/cats/new.html.erb
<h1>New cat</h1>

<%= render "form", cat: @cat %>

<br>

<div>
  <%= link_to "Back to cats", cats_path %>
</div>

app/views/cats/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @cat %>

<div>
  <%= link_to "Edit this cat", edit_cat_path(@cat) %> |
  <%= link_to "Back to cats", cats_path %>

  <%= button_to "Destroy this cat", cat_path(@cat), method: :delete %>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireBlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-light">

    <main class="min-vh-100">
      <%= render "shared/navbar" %>
      <%= render "shared/messages" %>
      <div class="container mt-5">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="scaffold_record">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <%= link_to "Show this post", post %>
  </p>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Post</h1>

<div id="posts">
  <%= render @posts %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", post_path(@post), method: :delete %>
</div>

app/views/shared/_messages.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show mt-2 mx-5 text-center" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-info alert-dismissible fade show  m-5" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm">
  <div class="container">
    <%= link_to "Hotwire Blog", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="navbar-nav me-auto mb-2 mb-lg-0">
          <%= link_to "Home", root_path, class: "nav-link" %>
          <%= link_to "Articles", articles_path, class: "nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav mb-2 mb-lg-0 dropdown">
        <% if logged_in? %>
          <a class="nav-link dropdown-toggle mr-2" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= image_tag avatar_path(current_user, size: 40), width: 20, height: 20, class: "rounded me-1" %>
            <%= current_user.name %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "Profile", user_path(current_user.slug), class: "dropdown-item nav-link" %></li>
            <li><%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item nav-link" %></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><%= button_to "Sign out", sign_out_session_path, method: :delete, class: "dropdown-item nav-link border-0 bg-transparent" %></li>
          </ul>
        <% else %>
          <li> <%= link_to "Sign up", new_user_path, class: "nav-item nav-link" %></li>
          <li><%= link_to "Login", session_path, class: "nav-item nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/edit.html.erb
<section class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-12 col-lg-5 mx-auto">
        <div class="card shadow-sm">
          <div class="card-body p-5">
            <span class="text-muted" data-config-id="caption">Edit</span>
            <h3 class="fw-bold mb-5" data-config-id="form-header">Edit Profile</h3>
            <% if @user.errors.any? %>
              <div class="alert alert-danger" role="alert">
                <ul>
                  <% @user.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <%= form_with model: @user do |form| %>
              <div class="form-group mb-3">
                <%= form.label :name, class: 'form-label mb-0 ms-1' %>
                <%= form.text_field :name, class: 'form-control mb-3', placeholder: 'Name' %>
              </div>

              <div class="form-group mb-3">
                <%= form.label :email, class: 'form-label mb-0 ms-1' %>
                <%= form.email_field :email, class: 'form-control mb-3', placeholder: 'E-mail Address' %>
              </div>

              <div class="form-group mb-3">
                <%= form.label :password, class: 'form-label mb-0 ms-1' %>
                <%= form.password_field :password, class: 'form-control mb-3', placeholder: 'Password' %>
              </div>

              <div class="form-group mb-3">
                <%= form.label :password_confirmation, class: 'form-label mb-0 ms-1' %>
                <%= form.password_field :password_confirmation, class: 'form-control mb-3', placeholder: 'Password confirmation' %>
              </div>

              <div class="d-flex justify-content-between">
              <%= form.submit 'Update', class: 'btn btn-primary my-3' %>
              <%= link_to 'Cancel', user_path(current_user), class: 'btn btn-outline-primary my-3' %>
              </div>
            <% end %>

            <p class="text-muted">
              <small>
              </small>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/new.html.erb
<section class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-12 col-lg-5 mx-auto">
        <div class="card shadow-sm">
          <div class="card-body p-5">
            <span class="text-muted" data-config-id="caption">Sign Up</span>
            <h3 class="fw-bold mb-3" data-config-id="form-header">Create new account</h3>
            <% if @user.errors.any? %>
              <div class="alert alert-danger" role="alert">
                <ul>
                  <% @user.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <%= form_with model: @user do |form| %>
              <%= form.text_field :name, class: 'form-control mb-3', placeholder: 'Name' %>
              <%= form.email_field :email, class: 'form-control mb-3', placeholder: 'E-mail Address' %>
              <%= form.password_field :password, class: 'form-control mb-3', placeholder: 'Password' %>
              <%= form.password_field :password_confirmation, class: 'form-control mb-3', placeholder: 'Password confirmation' %>
              <%= form.submit 'Sign Up', class: 'btn btn-primary py-2 w-100 mb-3' %>
            <% end %>

            <p class="text-muted">
              <small>
              </small>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<div class="row justify-content-md-center">
  <div class="col-12 bg-white p-4">
    <div class="d-flex justify-content-center">
      <%= image_tag avatar_path(current_user), width: 80, height: 80, class: "rounded-circle me-2" %>
      <div class="">
        <h1 class="mb-0"><%= current_user.name %></h1>
        <%= link_to "Edit profile", edit_user_path(current_user), class: "btn btn-link ms-4 p-0 border-0" %>
      </div>
    </div>

    <div class="row mt-5">
      <div class="offset-1 col-10">
        <div class="d-flex justify-content-between align-items-center mb-3">
          <h1>User's Articles</h1>
          <%= link_to "New Article", new_user_article_path(current_user.id), class: "btn btn-primary" %>
        </div>
        <% if @user.articles.any? %>
          <hr />
          <% @user.articles.desc_order.each do |article| %>
            <%= render partial: "articles/article", locals: { article: article } %>
          <% end %>
        <% else %>
          You have not published articles at this time
        <% end %>
      </div>
    </div>
  </div>

</div>